### ISSUE TITLE
Use environment variables for configuration-related options

### ISSUE THREAD

**Issue by rl555** [ftsrg/gazer#31]
It is hard to set up a development environment for Gazer and Theta. Of course, one must do it only once, but it would be nice to improve this :)

The problem I've come across is: When running `make check-functional`, there is no way of passing where are the libraries and jar file. If, as it is for `$GAZER_TOOLS_DIR`, an environment variable was used, one would easily be able to use `make check-functional` and `tools/gazer-theta` without a bloated parameter list.

Developing theta and gazer side-by-side is a pain (as one *must* use that `--theta-path` parameter, which is impossible sometimes).

Create environment variables that are passed to Theta, instead of passing them as arguments.
This removes coupling to the certain versions of Theta (which might become a problem), and also helps configuring a workspace for developing Theta and Gazer.

This is related to only configuration, e.g. where libz3 resides or where to find the jar file.

Also, I'm okay with an _let's do both_ way, that configuration passed as environment variables are overriden by the parameters. (Setting both `--theta-path` and (e.g.) `THETA_JAR` envvar the `--theta-path` takes precedence).

**Comment by sallaigy** [comment]
I agree, it is rather cumbersome to provide the Theta location. However why is providing `--theta-path` impossible?

Regardless, I am all for supporting environment variables. I think we can have the following lookup order:

1. The value of `--theta-path`, if set.
2. The value of `THETA_JAR`, if set.
3. The directory containing the `gazer-theta` binary.

We can do the same for `--lib-path`. I also think it would be worthwhile to come up with a default for the library path based on the JAR path.

**Comment by radl97** [comment]
> However why is providing --theta-path impossible?
For testing, `make check-functional` (and maybe neither `lit` tool) does not have a way to set up arguments as I want to.

> lookup order
Looks good to me.

> same for `--lib-path`
I'm all for it.

> default `--lib-path` when the path to the jar is set.
(if I understood correctly)
For now, my main goal would be to set up a convenient way to develop gazer and theta concurrently.
That's why I would support '<theta>/subprojects/<project>-cli/build/libs/*-all.jar` to `<theta>/lib` relative path from the JAR file. (`../../../../lib`).

Also, I would like to pass all environment variables to the theta runnable. It's not a main concern, but I think Theta would also benefit overriding default options.

My devised solution would be to

    pass all environment variables as is, except for THETA_JAR and THETA_LIB, which can be skipped

For both, I would support the order:

`parameter > envvar > tools directory`

Just as what you've written.
