### ISSUE TITLE
Gitignore for portfolio

### ISSUE THREAD

**Issue by radl97** [ftsrg/gazer#88]
Executing Portfolio test created a file that is not ignored by git.

It seems that the file `test/portfolio/0` is supposed to be a logfile of some kind. Maybe this file is created in `test/portfolio/` instead of inside `test/portfolio/Output`?

**Comment by AdamZsofi** [comment]
I saw that 0 before a few times, but I thought it disappeared with another small fix. 
Can you share the command (or one of the commands) used? 
I'll try to reproduce and take a look at it.

**Comment by radl97** [comment]
I just ran `make check-functional` and then it showed up in `git status`.
Working in master branch, even tested with `GAZER_TOOLS_DIR=$PWD/build/tools/ lit test/portfolio/`.

**Note:** The test fails for me, probably because of LLVM9 was not properly installed, maybe that triggers the bug.

**Comment by AdamZsofi** [comment]
There was a typo, when creating the logfile (I tried blaming `perl-tidy` for it, but I couldn't reproduce the thing, so it was probably my fault), which instead of concatenating the filename, tried to divide two strings, but instead of dying it returned 0.

Patched it on the branch `portfolio-patch`, but there is a good chance, that I'll need to patch a few other things in the coming days, so I'll merge only afterwards.
